Implement UID file object backup files and recovery processing.
ARMmbed/psa_trusted_storage_linux pull request #13
Opened 2019-10-18 15:06 UTC by simonqhughes

The following provides more information on this commit:
- UID data is stored in object files. To improve robustness against power
  failure, a copy of the xxxx.dat file is stored in a xxxx.bak file. In the
  case that the xxxx.dat file is lost and an xxxx.bak file remains, the
  xxxx.dat file is restored from the backup file.
- The backup file and recovery algorithm are described in detail in the
  PSA trusted storage Low Level Design (LLD) markdown file.
- Test cases have been implemented in the psa-storage-example-app to verify the
  correct operation of the recovery processing code. The test cases are
  described in the LLD.

2019-10-21 10:51 UTC, jainvikas8 commented on inc/config.h
> + * Define the this symbol to build a module test code into the library
Define this*

2019-10-21 11:08 UTC, jainvikas8 commented on docs/psa_trusted_storage_lld.md
> +The current design is not Robust Against Power Failure (RAPF) because the Linux filesystem underlying ecryptfs (i.e. ext4) is susceptible to being left in an inconsistent state. This is because the f
Tools like fsck exist to restore filesystem metadata consistency when the corruption of these data structures takes place.

2019-10-21 11:11 UTC, jainvikas8 commented on docs/psa_trusted_storage_lld.md
> +1.    A file object exists called file1.dat, which has a backup file called file1.bak.x where x={0,1}. file1.tmp and file1.bak.x have identical object data.
Bullets and numbering, please.

2019-10-21 11:29 UTC, jainvikas8 commented on docs/psa_trusted_storage_lld.md
> +    1. If xxxx.bkx(new) exists then use it to recreate xxxx.dat using the modification procedure.
It would be good to mention - xxxx.bak.yyyy (new) and xxxx.bak.xxxx (old)?

2019-10-28 13:38 UTC, simonqhughes commented on docs/psa_trusted_storage_lld.md
> +1.    A file object exists called file1.dat, which has a backup file called file1.bak.x where x={0,1}. file1.tmp and file1.bak.x have identical object data.
If you look at the .md file in a browser you'll see the multiple "1." are rendered as an ordered list. Do this resolve your request?

2019-10-28 13:38 UTC, simonqhughes commented on docs/psa_trusted_storage_lld.md
> +The current design is not Robust Against Power Failure (RAPF) because the Linux filesystem underlying ecryptfs (i.e. ext4) is susceptible to being left in an inconsistent state. This is because the f
I dont understand your comment here. Is there are spelling or type mistake?

2019-10-28 13:45 UTC, simonqhughes commented on docs/psa_trusted_storage_lld.md
> +    1. If xxxx.bkx(new) exists then use it to recreate xxxx.dat using the modification procedure.
Not sure exactly what you mean here. Are you saying that I better define terms? Are you saying:
- rather than referring to `xxxx.bak.yyyy (new)` in the text it would be better to use `xxxx.bak.yyy+1` ? 
- rather than referring to `xxxx.bak.yyyy (old)` in the text it would be better to use `xxxx.bak.yyy` ?

2019-11-04 14:09 UTC, simonqhughes commented on docs/psa_trusted_storage_lld.md
> +    1. If xxxx.bkx(new) exists then use it to recreate xxxx.dat using the modification procedure.
@jainvikas8 In conversation you asked me to fix this document so it uses a consistent naming convention for files when describing the procedure for restoring files from backups. AS discussed, the plan is to remove the lld from the PR. However, I've updated the HLD https://confluence.arm.com/display/mbedlinux/PSA+Storage+Software+HLD in the section "Robustness Against Power Failure (RAPF)" to use consistent naming. The LLD documentation was taken from here.

2019-11-04 17:26 UTC, simonqhughes commented on docs/psa_trusted_storage_lld.md
> +1.    A file object exists called file1.dat, which has a backup file called file1.bak.x where x={0,1}. file1.tmp and file1.bak.x have identical object data.
psa_truste_storage_lld.md has now been removed.

2019-11-04 17:28 UTC, simonqhughes commented on inc/config.h
> + * Define the this symbol to build a module test code into the library
Fixed.

2019-11-06 08:36 UTC, jainvikas8 commented on lib/common_storage.c
> + * See the PSA Trusted Storage Linux Low Level Design docmment in the docs subdirectory
I think the statement would not make any sense, as the documentation is removed?

2019-11-06 10:06 UTC, jainvikas8 commented on lib/common_storage.c
> +    psa_assert( psa_cs_num_file_objects == 3 );
const define, seeing this used most of the places?

2019-11-06 10:06 UTC, jainvikas8 commented on lib/common_storage.c
> +      3 +                                       /* "_" and 8-bit sequence number */         \
Would it be suitable to make it a constant/define if it is used in many places?

2019-11-06 12:05 UTC, simonqhughes commented on lib/common_storage.c
> +    psa_assert( psa_cs_num_file_objects == 3 );
Added define.

2019-11-06 12:06 UTC, simonqhughes commented on lib/common_storage.c
> +      3 +                                       /* "_" and 8-bit sequence number */         \
Added define.

2019-11-06 12:06 UTC, simonqhughes commented on lib/common_storage.c
> + * See the PSA Trusted Storage Linux Low Level Design docmment in the docs subdirectory
Removed.

2019-11-08 11:51 UTC, simonqhughes commented
Further review comments from Vikas from Simon/Vikas review meeting 20191107:
- Correct  PSA Stroage HLD RAPF picture:
  - correct (3) <-> (4)
  - add (6) for deleting old .bak file
  - remove seqnum and use yyy, and clearly defined that yyy is the sequence number
  - remove (yyy) from being appended to filenames and show them in the files.
- The `<uid>.tmp` file can be used for recovery under the following conditions:
    - A `<uid>.tmp(yyy+1)` file exists (with a seqnum yyy+1) but there is no `<uid>_yyy+1.bak` and no `<uid>.dat(yyy+1)`. (if the `<uid>_yyy+1.bak` then it can be used for recovery)
         This state can be detected by one of the following states:
             - a. A `<uid>_yyy.bak` file exists, or
             - b. A `<uid>.dat(yyy)` file exists.
         If the fact that that the `<uid>.tmp` sequence number has been updated indicates then `<uid>.tmp` file can be used to create `<uid>.dat(yyy+1)` in the absence of this file and the `<uid>_yyy+1.bak`
- Is there the possibility of that the `<uid>_yyy+1.bak` file can be left in a damaged half written state due to power failure?
- Where are what the test cases do documented?
- As part of the output of running the test cases, output a description of what the test case does.
- Make sure _DEBUG flag and the _TEST flag are independent.
- Add documentation about the methodology of how to add new test cases.
- Debug trace should output start/end of a particular test.

2019-11-08 16:07 UTC, simonqhughes commented
With respect to the 20191107 feedback from Vikas:
1. Item 1) has been addressed by updating the RAPF picture are requested. See the latest version of the HLD here: https://confluence.arm.com/display/mbedlinux/PSA+Storage+Software+HLD
2. It is possible to use the <uid>.tmp file for recovery under the described scenario. However, this hasn't been done in the current work. I've created a jira ticket for implementing this improvement here:

2019-11-12 17:20 UTC, simonqhughes commented
The following is a review question from Vikas:
>> Is there the possibility of that the <uid>_yyy+1.bak file can be left in a damaged half written state due to power failure?
It is not possible for the .bak file to be left in a damaged half written state because the full file is written to temporary file. Once written the file is then renamed to the .bak file with the POSIX rename() function, which is an atomic filesystem operation. Therefore the <uid>_yyy+1.bak either does not exist, or exists in its complete form.

The above

2019-11-13 17:29 UTC, simonqhughes commented
@jainvikas8 I've worked through your feedback and acted upon it. Please review again.

2019-11-14 15:46 UTC, jainvikas8 commented on lib/common_storage.c
> + *  Generate a temporary filename using using an internal counter.
Typo/Grammer error

2019-11-14 16:37 UTC, jainvikas8 requested changes

2019-11-14 16:37 UTC, jainvikas8 commented on lib/common_storage.c
> +    /* As all files are stored on encrypted file system, a request for no confidentiality
Typo/Grammer

2019-11-14 16:37 UTC, jainvikas8 commented on lib/common_storage.c
> +        /* Step 1: Copy to pre-existing file to a tmp file.
Typo/Grammer

2019-11-14 16:37 UTC, jainvikas8 commented on lib/common_storage.c
> +    /* NB: have to decrement sequence number supplied to _set() because creation of bak files will be
Typo/Grammer

2019-11-14 16:37 UTC, jainvikas8 commented on lib/common_storage.c
> +    /* NB: have to decrement sequence number supplied to _set() because creation of bak files will be
Typo/Grammer

2019-11-14 16:37 UTC, jainvikas8 commented on lib/common_storage.c
> + *  Create a other uid files so there are present during recovery processing
Typo/Grammer

2019-11-14 16:37 UTC, jainvikas8 commented on lib/common_storage.c
> +    status = psa_cs_remove( PSA_CS_TEST_UID1, state->api );
Could it be done in a loop with 2 different UID?

2019-11-14 16:37 UTC, jainvikas8 commented on lib/common_storage.c
> +    get_filename_flags = PSA_CS_GET_FILENAME_F_BA
Could it be done in a loop with 2 different UID?

2019-11-14 16:37 UTC, jainvikas8 commented on lib/common_storage.c
> +    get_filename_flags = PSA_CS_GET_FILENAME_F_BA
Could it be done in a loop with 2 different UID?

2019-11-14 16:37 UTC, jainvikas8 commented on lib/common_storage.c
> +    get_filename_flags = PSA_CS_GET_FILENAME_F_BA
Could it be done in a loop with 2 different UID?

Why don't we call a function to perform these steps which are generic for a UID and use it?

2019-11-14 16:37 UTC, jainvikas8 commented on lib/common_storage.c
> +    get_filename_flags = PSA_CS_GET_FILENAME_F_BA
Why don't we call a function to perform these steps which are generic for a UID and use it?

2019-11-14 16:37 UTC, jainvikas8 commented on lib/common_storage.c
> +    get_filename_flags = PSA_CS_GET_FILENAME_F_BA
Why don't we call a function to perform these steps which are generic for a UID and use it?

2019-11-14 16:37 UTC, jainvikas8 commented on app/main.c
> +            "TC053: Rcvr .dat (1 .dat(new, mismatched), 1 .bak, F_WRITE_ONCE unset) %s\n",
"TC053: Rcvr .dat (1 .dat (new, mismatched), 1 .bak, F_WRITE_ONCE unset)

2019-11-19 17:48 UTC, simonqhughes commented on lib/common_storage.c
> + *  Generate a temporary filename using using an internal counter.
Fixed.

2019-11-19 17:48 UTC, simonqhughes commented on lib/common_storage.c
> + *   src_filename       name of file to copy
Fixed.

2019-11-19 17:48 UTC, simonqhughes commented on lib/common_storage.c
> + *  Open and read the file object header given a filename.
Fixed.

2019-11-19 17:48 UTC, simonqhughes commented on lib/common_storage.c
> + *   p_info      IN, pointer to information structure to take copy of in psa_storage_info_t stored in file.
Fixed.

2019-11-19 17:48 UTC, simonqhughes commented on lib/common_storage.c
> +     * If only bka exists then state->bkb_seqnum = 0 and then this doesnt work for
Fixed.

2019-11-19 17:48 UTC, simonqhughes commented on lib/common_storage.c
> +     * If only bka exists then state->bkb_seqnum = 0 and then this doesnt work */
Fixed.

2019-11-19 17:48 UTC, simonqhughes commented on lib/common_storage.c
> +    /* As all files are stored on encrypted file system, a request for no confidentiality
Fixed.

2019-11-19 17:48 UTC, simonqhughes commented on lib/common_storage.c
> +        /* Step 1: Copy to pre-existing file to a tmp file.
Fixed.

2019-11-19 17:49 UTC, simonqhughes commented on lib/common_storage.c
> +    /* NB: have to decrement sequence number supplied to _set() because creation of bak files will be
Fixed.

2019-11-19 17:49 UTC, simonqhughes commented on lib/common_storage.c
> +    /* NB: have to decrement sequence number supplied to _set() because creation of bak files will be
Fixed.

2019-11-19 17:49 UTC, simonqhughes commented on lib/common_storage.c
> + *  Create a other uid files so there are present during recovery processing
Fixed.

2019-11-19 17:50 UTC, simonqhughes commented on lib/common_storage.c
> +    status = psa_cs_remove( PSA_CS_TEST_UID1, state->api );
Fixed.

2019-11-19 17:57 UTC, simonqhughes commented on lib/common_storage.c
> +    get_filename_flags = PSA_CS_GET_FILENAME_F_BA
Fixed.

2019-11-19 17:57 UTC, simonqhughes commented on lib/common_storage.c
> +    get_filename_flags = PSA_CS_GET_FILENAME_F_BA
Fixed.

2019-11-19 17:58 UTC, simonqhughes commented on lib/common_storage.c
> +    get_filename_flags = PSA_CS_GET_FILENAME_F_BA
Fixed.

2019-11-19 17:58 UTC, simonqhughes commented on lib/common_storage.c
> +    get_filename_flags = PSA_CS_GET_FILENAME_F_BA
Fixed.

2019-11-19 17:59 UTC, simonqhughes commented on app/main.c
> +            "TC053: Rcvr .dat (1 .dat(new, mismatched), 1 .bak, F_WRITE_ONCE unset) %s\n",
Please can you expand your statement here. Your comment doesn't ask for a specific change.

2019-11-19 18:00 UTC, simonqhughes commented
@jainvikas8  I've acted upon the outstanding feedback. Please review again. Thanks.

2019-11-19 20:24 UTC, jainvikas8 approved these changes

2019-11-20 09:31 UTC, merged

2019-11-20 09:32 UTC, simonqhughes commented
@jainvikas8 Many thanks for doing this review. Perhaps I can do the same for you sometime.