Add multi-process, multi-thread and PSA storage partition support.
ARMmbed/psa_trusted_storage_linux pull request #17
Opened 2019-12-18 17:02 UTC by simonqhughes

The following provides more information on this commit:
- Add getuid() user ID to file object basename. The user ID is used as the
  partition identifier.
- Add process and thread IDs to temporary filename basename. This makes accesses
  to the temporary files process and thread safe, as there is only 1 temporary
  file in existence at a time.
- Make mktemp_filename() temporary filenames process and thread safe.
- Add psa_test_case_201.sh for multi-process multi-thread testing.
- Add additional test cases to psa-storage-example-app for multi-process
  multi-thread testing.

2019-12-20 10:52 UTC, diego-sueiro requested changes

2019-12-20 10:52 UTC, diego-sueiro commented on test/psa_test_case_201.sh
> +        sudo useradd ${user}
Have you tested this in one of our targets?
Our images don't have `bash` and `sudo` for example. How this is script ran on imx8?

2019-12-20 12:11 UTC, simonqhughes commented on test/psa_test_case_201.sh
> +        sudo useradd ${user}
The script is for testing on x86.

2019-12-20 13:53 UTC, diego-sueiro commented on test/psa_test_case_201.sh
> +        sudo useradd ${user}
Right. Can you please add a comment in the script about this.
Also, the other tests from `test/Makefile` are supposed to run only on x86?

Is there any plan to have these tests running on our supported platforms?

2019-12-20 14:44 UTC, diego-sueiro commented on test/psa_test_case_201.sh
> +        sudo useradd ${user}
I also think that the instructions that you put on the top of the `test/Makefile` should go into a `test/README.md` file.

2020-01-06 12:07 UTC, simonqhughes commented on test/psa_test_case_201.sh
> +        sudo useradd ${user}
>> Have you tested this in one of our targets?

Yes, on imx8. The test output shown in the PR summary shows the test results collected on imx8.

2020-01-07 11:40 UTC, diego-sueiro commented on test/psa_test_case_201.sh
> +        sudo useradd ${user}
But you said earlier that this script is for testing on x86.

2020-01-07 11:42 UTC, diego-sueiro commented
I think we should bump the version for this implementation and also add the version information in the Makefile alongside with a git tag. The `psa-trusted-storage-linux` recipe name will also need to be updated.

2020-01-07 13:17 UTC, simonqhughes commented on test/psa_test_case_201.sh
> +        sudo useradd ${user}
>> But you said earlier that this script is for testing on x86.

The documentation in the following HLD (https://confluence.arm.com/display/mbedlinux/PSA+Storage+Software+HLD) sections help answer this question.
- Test Case 201: Multi-process support test
- Test Case 203: Multi-process-multi-thread support test

If these sections are insufficient then lets discuss together the details.

2020-01-07 13:25 UTC, simonqhughes commented on test/psa_test_case_201.sh
> +        sudo useradd ${user}
>> Right. Can you please add a comment in the script about this.

Yes, I'll do that.

>> Also, the other tests from test/Makefile are supposed to run only on x86?

The short answer is no. Testing can be performed on x86 and on-target. Here are some more details to explain this:
- The project builds a test application (`psa-storage-example-app`). This is build to include the test cases.
- `psa-storage-example-app` can be run on target.
- `psa-storage-example-app` can be also be built for x86, and run multiple times in parallel with the `psa_test_case_201.sh` bash script.

2020-01-07 15:50 UTC, simonqhughes commented on test/psa_test_case_201.sh
> +        sudo useradd ${user}
>> Right. Can you please add a comment in the script about this.

The above feedback comment has been addressed with commit https://github.com/ARMmbed/psa_trusted_storage_linux/pull/17/commits/00cf943e90fdff4e9f6287f8ff5368a5cbd8d5af.

2020-01-07 16:15 UTC, simonqhughes commented on test/psa_test_case_201.sh
> +        sudo useradd ${user}
>> I also think that the instructions that you put on the top of the test/Makefile should go into a test/README.md file.

The above feedback comment has been addressed with commit https://github.com/ARMmbed/psa_trusted_storage_linux/pull/17/commits/ff7c3205cf389cca773aee433e7fc1146be4e7b8

2020-01-07 16:18 UTC, rwalton-arm commented on app/main.c
>      const char* tc_description[] = {
This array should be `static const char*` if we're not mutating it later on in the code.

2020-01-07 16:56 UTC, simonqhughes reviewed
>> Can you please explain me the tag layout structure used in this repo?

Jezz settled on the following policy. Tags are created for the downstream consumers e.g. the PDMC team (Jenia Kogan et al.) for their releases. There has only been 1 tag created for them: `ptsl-0.0.1-psa-storage-api-1.0.0`. 
- `pstl` is the acronym from the name of this repo (PSA Trusted Storage Linux).
- The first version tuple is specified by us. When we tag, i suggest this version tuple should match whats in `<topdir>/Makefile`.
- `psa-storage-api` qualifies the second version tuple.
- The second version tuple is the version of the PSA Storage API supported by the implementation. 

>> I think we should bump the version for this implementation

OK, but I think this needs some discussion. Consider:
- If we're following the above policy there is no need to bump the version until the next "release" is made.
- The tuple `1.0.0` hasn't been used in a release yet.
- The `ptsl-0.0.1-psa-storage-api-1.0.0` tag sha is the one that appears in the `meta-mbl psa-trusted-storage-linux_1.0.0.bb` recipe. The Makefile version information is not present in `ptsl-0.0.1-psa-storage-api-1.0.0::<topdir>/Makefile`. Perhaps this inconsistency is best corrected by renaming `psa-trusted-storage-linux_1.0.0.bb` to `psa-trusted-storage-linux_0.0.1.bb`? When the recipe sha is updated to point to tuple x.y.z then we can rename the recipe to `psa-trusted-storage-linux_x.y.z.bb`.

>> and also move the version information in the Makefile to the top of the file

Do you mean move <topdir>/Makefile lines 23-25 to lines 16-18?

>>  alongside with a git tag

Do you mean adding a comment which specifies a git tag thats created after the PR is merged? or something else?

2020-01-08 09:25 UTC, diego-sueiro commented
> > > Can you please explain me the tag layout structure used in this repo?
> 
> Jezz settled on the following policy. Tags are created for the downstream consumers e.g. the PDMC team (Jenia Kogan et al.) for their releases. There has only been 1 tag created for them: `ptsl-0.0.1-psa-storage-api-1.0.0`.
> 
> * `pstl` is the acronym from the name of this repo (PSA Trusted Storage Linux).
> * The first version tuple is specified by us. When we tag, i suggest this version tuple should match whats in `<topdir>/Makefile`.
> * `psa-storage-api` qualifies the second version tuple.
> * The second version tuple is the version of the PSA Storage API supported by the implementation.
> 

Understood. Thanks. And yes, the version information in the project Makefile must match the first version tuple.

> > > I think we should bump the version for this implementation
> 
> OK, but I think this needs some discussion. Consider:
> 
> * If we're following the above policy there is no need to bump the version until the next "release" is made.

As I understand, we are delivering a new features for PSA Storage supporting multi-process/multi-threads. To _celebrate_ this I think we have to bump at least the `rel` version.

> * The tuple `1.0.0` hasn't been used in a release yet.
> * The `ptsl-0.0.1-psa-storage-api-1.0.0` tag sha is the one that appears in the `meta-mbl psa-trusted-storage-linux_1.0.0.bb` recipe. The Makefile version information is not present in `ptsl-0.0.1-psa-storage-api-1.0.0::<topdir>/Makefile`. Perhaps this inconsistency is best corrected by renaming `psa-trusted-storage-linux_1.0.0.bb` to `psa-trusted-storage-linux_0.0.1.bb`? When the recipe sha is updated to point to tuple x.y.z then we can rename the recipe to `psa-trusted-storage-linux_x.y.z.bb`.
This needs to be fixed in the recipe name.

> 
> > > and also move the version information in the Makefile to the top of the file
> 
> Do you mean move /Makefile lines 23-25 to lines 16-18?
> 

Yes, and we should not use the `?=` assignment for the versioning setting.

> > > alongside with a git tag
> 
> Do you mean adding a comment which specifies a git tag thats created after the PR is merged? or something else?

No. What I meant was: if we bump the version in the make file we need to create a new tag (following the proposed tag layout policy).

2020-01-08 12:02 UTC, simonqhughes commented
>> To celebrate this I think we have to bump at least the rel version.

>> Yes, and we should not use the ?= assignment for the versioning setting.

The `<topdir>/Makefile` version information has been fixed in commit https://github.com/ARMmbed/psa_trusted_storage_linux/pull/17/commits/e06a7623ac5fba923cabf6c3e4662a6f287d15ea

2020-01-08 12:02 UTC, simonqhughes commented on app/main.c
>      const char* tc_description[] = {
Fixed in https://github.com/ARMmbed/psa_trusted_storage_linux/pull/17/commits/3814d49ae609c6052baf68494f6585eecf4b1324.

2020-01-08 12:12 UTC, diego-sueiro commented
> > > To celebrate this I think we have to bump at least the rel version.
> 
> > > Yes, and we should not use the ?= assignment for the versioning setting.
> 
> The `<topdir>/Makefile` version information has been fixed in commit [e06a762](https://github.com/ARMmbed/psa_trusted_storage_linux/commit/e06a7623ac5fba923cabf6c3e4662a6f287d15ea)

Shouldn't be 0.0.2? Why the major version is 1? I think we agreed that the version in the Makefile must match with the first version tuple of the git tag `ptsl-x.y.z-psa-storage-api-1.0.0`. So we need to have on the Makefile:
```
major = x
minor = y
rel  = z
```

2020-01-08 13:13 UTC, simonqhughes commented
>> Shouldn't be 0.0.2? 

Fixed in https://github.com/ARMmbed/psa_trusted_storage_linux/pull/17/commits/9ad6f0959b6adbd28614da09bed4a37048fcf12f

2020-01-09 09:35 UTC, diego-sueiro requested changes

2020-01-09 09:35 UTC, diego-sueiro commented on app/Makefile
> +CFLAGS ?=
These lines can be removed.

2020-01-09 09:35 UTC, diego-sueiro commented on lib/Makefile
> +CFLAGS ?=
These lines can be removed.

2020-01-09 09:35 UTC, diego-sueiro commented on lib/Makefile
> +LOCAL_LDFLAGS ?= -shared -lpthread
`?=` shouldn't be used and the `-lpthread` should be passed when `PSA_STORAGE_TEST` is present. You can have something like this:
```
LOCAL_LDFLAGS = -shared
ifeq ($(PSA_STORAGE_TEST),1)
LOCAL_LDFLAGS += -lpthread 
CFLAGS += -DPSA_STORAGE_TEST
endif
```

Then the make command for the test can be something like:
```
make PSA_STORAGE_TEST=1
```

2020-01-09 09:35 UTC, diego-sueiro commented on test/Makefile
> +
In some lines bellow, for the `ws-create` and `ws-create-pinned` targets, why are you doing `repo init -u https://github.com/armmbed/mbl-manifest`?

These steps are very confusing. You are cloning the `psa_trusted_storage_linux` repo again. Why? If the repo is already cloned you don't need to clone it again, copy the manifest and sync. This is overcomplicated. You could have something link this:
```
repo init -u https://github.com/ARMmbed/psa_trusted_storage_linux -m test/psa-storage-test-manifest.xml
```

Also, please get rid of the ssh protocol URLs on this Makefile and on the manifests. All repos are public and we can use the https.

2020-01-09 09:35 UTC, diego-sueiro commented on test/README.md
> +(WARNING: Public users will be unable to use this makefile to generate
I don't think we have nay private repo.

2020-01-09 09:35 UTC, diego-sueiro commented on test/README.md
> + - A private fork of https://github.com/ARM-software/psa-arch-tests. The private
The fork is not private.

2020-01-09 09:35 UTC, diego-sueiro commented on test/psa_test_case_201.sh
> +# !/bin/bash
```suggestion
#!/bin/bash
```

2020-01-09 09:35 UTC, diego-sueiro commented on test/psa_test_case_201.sh
> +# !/bin/bash
Can you please run and fix the errors reported by the shellcheck in this file?

2020-01-09 13:21 UTC, simonqhughes commented on test/psa_test_case_201.sh
> +# !/bin/bash
Will do.

2020-01-09 13:21 UTC, simonqhughes commented on test/README.md
> + - A private fork of https://github.com/ARM-software/psa-arch-tests. The private
Yes, will fix.

2020-01-09 13:21 UTC, simonqhughes commented on test/README.md
> +(WARNING: Public users will be unable to use this makefile to generate
Agree, will fix this.

2020-01-09 14:29 UTC, simonqhughes commented on test/psa_test_case_201.sh
> +# !/bin/bash
`shellcheck` changes added in commit https://github.com/ARMmbed/psa_trusted_storage_linux/pull/17/commits/0641e0421c3edc5dbae6fc460a32c75f034d3929.

2020-01-10 16:28 UTC, diego-sueiro requested changes

2020-01-10 16:28 UTC, diego-sueiro commented on lib/common_storage.c
> +#include <sys/syscall.h>    /* for gittid() */
```suggestion
#include <sys/syscall.h>    /* for gettid() */
```

2020-01-10 16:28 UTC, diego-sueiro commented on lib/common_storage.c
> +/* PSA_CS_FILENAME_XUID_PATTERN_LEN is the XUID pattern string length.
What is the length unit? Is it in bytes? Can you please specify it in the comment?

2020-01-10 16:28 UTC, diego-sueiro commented on lib/common_storage.c
> +/* PSA_CS_FILENAME_UID_PATTERN_LEN is the PSA_CS_FILENAME_UID_PATTERN string length. */
What is the length unit? Is it in bytes? Can you please specify it in the comment?

2020-01-10 16:28 UTC, diego-sueiro commented on lib/common_storage.c
> +/* PSA_CS_FILENAME_RUID_PATTERN_LEN is the PSA_CS_FILENAME_RUID_PATTERN string length. */
What is the length unit? Is it in bytes? Can you please specify it in the comment?

2020-01-10 16:28 UTC, diego-sueiro commented on lib/common_storage.c
> +/* PSA_CS_FILENAME_PATTERN_LEN is the PSA_CS_FILENAME_PATTERN string length. */
What is the length unit? Is it in bytes? Can you please specify it in the comment?

2020-01-10 16:28 UTC, diego-sueiro commented on lib/common_storage.c
> +/* PSA_CS_TMP FILENAME_PATTERN_LEN is the PSA_CS_FILENAME_PATTERN string length. */
What is the length unit? Is it in bytes? Can you please specify it in the comment?

2020-01-10 16:28 UTC, diego-sueiro commented on lib/common_storage.c
> +/* PSA_CS_PATH_FILENAME_LENGTH is the buffer length for the full path and filename of a file
What is the length unit? Is it in bytes? Can you please specify it in the comment?

2020-01-10 18:13 UTC, simonqhughes commented on test/README.md
> + - A private fork of https://github.com/ARM-software/psa-arch-tests. The private
Fixed in https://github.com/ARMmbed/psa_trusted_storage_linux/pull/17/commits/5206b43d1546c452d99c5c61624458c94670bcb5

2020-01-10 18:13 UTC, simonqhughes commented on test/README.md
> +(WARNING: Public users will be unable to use this makefile to generate
Fixed in https://github.com/ARMmbed/psa_trusted_storage_linux/pull/17/commits/5206b43d1546c452d99c5c61624458c94670bcb5

2020-01-10 18:13 UTC, simonqhughes commented on lib/Makefile
> +LOCAL_LDFLAGS ?= -shared -lpthread
Fixed in https://github.com/ARMmbed/psa_trusted_storage_linux/pull/17/commits/5206b43d1546c452d99c5c61624458c94670bcb5

2020-01-10 18:14 UTC, simonqhughes commented on lib/Makefile
> +CFLAGS ?=
Fixed in https://github.com/ARMmbed/psa_trusted_storage_linux/pull/17/commits/5206b43d1546c452d99c5c61624458c94670bcb5

2020-01-10 18:14 UTC, simonqhughes commented on app/Makefile
> +CFLAGS ?=
Fixed in https://github.com/ARMmbed/psa_trusted_storage_linux/pull/17/commits/5206b43d1546c452d99c5c61624458c94670bcb5

2020-01-10 18:15 UTC, simonqhughes commented on test/Makefile
> +
Fixed in https://github.com/ARMmbed/psa_trusted_storage_linux/pull/17/commits/2a19feccd83e088688d861e15faa7b26ae158821

2020-01-13 08:30 UTC, diego-sueiro requested changes

2020-01-13 08:30 UTC, diego-sueiro commented on lib/common_storage.c
> +        psa_debug( "Error: stat() failed with unexpected error (%d)\n", errno );
Error messages shouldn't be mixed with debug messages. If we don't compile with `PSA_STORAGE_DEBUG` we will miss important error messages.
I think you should have a `psa_error` or if you want a `psa_log` with log level feature (LOG_INFO, LOG_ERR etc).

2020-01-13 08:30 UTC, diego-sueiro commented on lib/common_storage.c
>  #include <string.h>
This source code file has ~4k lines of code.
I think it could be better modularized if you have the test code in a different file and the same thing for the recovery mechanism.

2020-01-13 12:07 UTC, rwalton-arm commented on inc/config.h
> + * of files is N * PSA_STORAGE_FILE_MAX.
How do we decide what value to give `PSA_STORAGE_FILE_MAX`? Is it arbitrary?

2020-01-13 12:51 UTC, rwalton-arm requested changes
Haven't finished reviewing yet, but I have a few comments/questions.

2020-01-13 12:51 UTC, rwalton-arm commented on lib/common_storage.c
> +    const pid_t tid = syscall(SYS_gettid);
We should check the return value for `syscall` and handle any errors explicitly. `syscall` will set `errno` and usually return -1 when it fails.

2020-01-13 12:51 UTC, rwalton-arm commented on lib/common_storage.c
> +    snprintf( tmps_filter, PSA_CS_TMP_FILENAME_LENGTH, PSA_CS_TMP_FILENAME_RUID_PID_TID_PATTERN, (unsigned long int) ruid, (unsigned long int) pid, (unsigned long int) tid );
We should check the return value of `snprintf` to ensure the concatenation succeeded and the output wasn't truncated.

2020-01-13 12:51 UTC, rwalton-arm commented on lib/common_storage.c
> +    const pid_t tid = syscall(SYS_gettid);
We should check the return value for `syscall` and handle any errors explicitly. `syscall` will set `errno` and usually return -1 when it fails.

2020-01-13 12:51 UTC, rwalton-arm commented on lib/common_storage.c
> +    snprintf( filename, len, "%s/" PSA_CS_TMP_FILENAME_RUID_PID_TID_PATTERN "%s", dname, (unsigned long int) ruid, (unsigned long int) pid, (unsigned long int) tid, PSA_CS_BAD_FILE_SUFFIX );
We should check the return value of `snprintf` to ensure the concatenation succeeded and the output wasn't truncated.

2020-01-13 12:51 UTC, rwalton-arm commented on lib/common_storage.c
> +        snprintf( filename, len,
errors?

2020-01-13 12:51 UTC, rwalton-arm commented on lib/common_storage.c
> +        tid = syscall(SYS_gettid);
errors?

2020-01-13 12:51 UTC, rwalton-arm commented on lib/common_storage.c
> +        snprintf( filename, len,
errors?

2020-01-13 12:51 UTC, rwalton-arm commented on lib/common_storage.c
> +        snprintf( filename, len,
errors?

2020-01-13 12:51 UTC, rwalton-arm commented on lib/common_storage.c
> +        tid = syscall(SYS_gettid);
errors?

2020-01-13 12:51 UTC, rwalton-arm commented on lib/common_storage.c
> +        status = PSA_SUCCESS;
Can we factor some of this repeated code out into helper functions?

2020-01-13 12:51 UTC, rwalton-arm commented on lib/common_storage.c
> +        status = PSA_ERROR_INVALID_ARGUMENT;
should we log these errors?

2020-04-14 15:30 UTC, simonqhughes commented
This PR is being closed due to the closure of this feature development. See the relevant confluence pages for more information.

2020-04-14 15:30 UTC, closed without merging

2020-04-14 15:35 UTC, simonqhughes commented on lib/common_storage.c
> +#include <sys/syscall.h>    /* for gittid() */
If this work is restarted, this change can be accepted.

2020-04-14 15:35 UTC, simonqhughes commented on lib/common_storage.c
> +/* PSA_CS_FILENAME_XUID_PATTERN_LEN is the XUID pattern string length.
If this work is restarted, this change can be made.

2020-04-14 15:35 UTC, simonqhughes commented on lib/common_storage.c
> +/* PSA_CS_FILENAME_UID_PATTERN_LEN is the PSA_CS_FILENAME_UID_PATTERN string length. */
If this work is restarted, this change can be made.

2020-04-14 15:35 UTC, simonqhughes commented on lib/common_storage.c
> +/* PSA_CS_FILENAME_RUID_PATTERN_LEN is the PSA_CS_FILENAME_RUID_PATTERN string length. */
If this work is restarted, this change can be made.

2020-04-14 15:35 UTC, simonqhughes commented on lib/common_storage.c
> +/* PSA_CS_FILENAME_PATTERN_LEN is the PSA_CS_FILENAME_PATTERN string length. */
If this work is restarted, this change can be made.

2020-04-14 15:35 UTC, simonqhughes commented on lib/common_storage.c
> +/* PSA_CS_TMP FILENAME_PATTERN_LEN is the PSA_CS_FILENAME_PATTERN string length. */
If this work is restarted, this change can be made.

2020-04-14 15:36 UTC, simonqhughes commented on lib/common_storage.c
> +/* PSA_CS_PATH_FILENAME_LENGTH is the buffer length for the full path and filename of a file
If this work is restarted, this change can be made.

2020-04-14 15:37 UTC, simonqhughes commented on lib/common_storage.c
> +        psa_debug( "Error: stat() failed with unexpected error (%d)\n", errno );
This isn't an error message per-se, its a debug message. However, if this work is restarted, the debug log message can be changed to make this clear.

2020-04-14 15:37 UTC, simonqhughes commented on lib/common_storage.c
>  #include <string.h>
Agreed, this modularisation would be better. If this work is restarted, this work can be considered.

2020-04-14 15:39 UTC, simonqhughes commented on inc/config.h
> + * of files is N * PSA_STORAGE_FILE_MAX.
It depends on how many simultaneously open files you want in the system. Its not arbitrary but sized to the maximum number of storage objects that should ever be present in the system.

2020-04-14 15:39 UTC, simonqhughes commented on lib/common_storage.c
> +    const pid_t tid = syscall(SYS_gettid);
Agreed. If this work is restarted, this work can be considered.

2020-04-14 15:39 UTC, simonqhughes commented on lib/common_storage.c
> +    snprintf( tmps_filter, PSA_CS_TMP_FILENAME_LENGTH, PSA_CS_TMP_FILENAME_RUID_PID_TID_PATTERN, (unsigned long int) ruid, (unsigned long int) pid, (unsigned long int) tid );
Agreed. If this work is restarted, this work can be considered.

2020-04-14 15:39 UTC, simonqhughes commented on lib/common_storage.c
> +    const pid_t tid = syscall(SYS_gettid);
Agreed. If this work is restarted, this work can be considered.

2020-04-14 15:40 UTC, simonqhughes commented on lib/common_storage.c
> +    snprintf( filename, len, "%s/" PSA_CS_TMP_FILENAME_RUID_PID_TID_PATTERN "%s", dname, (unsigned long int) ruid, (unsigned long int) pid, (unsigned long int) tid, PSA_CS_BAD_FILE_SUFFIX );
Agreed. If this work is restarted, this work can be considered.

2020-04-14 15:40 UTC, simonqhughes commented on lib/common_storage.c
> +        snprintf( filename, len,
Agreed. If this work is restarted, this work can be considered.

2020-04-14 15:40 UTC, simonqhughes commented on lib/common_storage.c
> +        tid = syscall(SYS_gettid);
Agreed. If this work is restarted, this work can be considered.

2020-04-14 15:40 UTC, simonqhughes commented on lib/common_storage.c
> +        snprintf( filename, len,
Agreed. If this work is restarted, this work can be considered.

2020-04-14 15:40 UTC, simonqhughes commented on lib/common_storage.c
> +        snprintf( filename, len,
Agreed. If this work is restarted, this work can be considered.

2020-04-14 15:40 UTC, simonqhughes commented on lib/common_storage.c
> +        tid = syscall(SYS_gettid);
Agreed. If this work is restarted, this work can be considered.

2020-04-14 15:41 UTC, simonqhughes commented on lib/common_storage.c
> +        status = PSA_SUCCESS;
Agreed. If this work is restarted, this work can be considered.

2020-04-14 15:41 UTC, simonqhughes commented on lib/common_storage.c
> +        status = PSA_ERROR_INVALID_ARGUMENT;
Possibly. However, this would make the implementation tied to a logging system and less portable.